### ISSUE TITLE
io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.

### ISSUE THREAD

**Issue by bigzengdotcom** [apache/servicecomb-pack#327]
After issue #326   

****i wrote a method (with @SagaStart) in another service named core-base-service to invoke addStaff Method of Staff Controller in membership service via spring feign .  and in addStaff mehod , it invoke save method (with @Compensable ) in StaffService.**

**when trying to invoke method with @SagaStart in core-base-service  ,   the exception follows:****

io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420) [grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:531) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.14.0.jar:1.14.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.apache.servicecomb.saga.omega.context.CallbackContext.apply(CallbackContext.java:50) ~[omega-context-0.3.0.jar:0.3.0]
	at org.apache.servicecomb.saga.omega.transaction.CompensationMessageHandler.onReceive(CompensationMessageHandler.java:35) ~[omega-transaction-0.3.0.jar:0.3.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.sun.proxy.$Proxy186.onReceive(Unknown Source) ~[na:na]
	at org.apache.servicecomb.saga.omega.connector.grpc.saga.GrpcCompensateStreamObserver.onNext(GrpcCompensateStreamObserver.java:52) ~[omega-connector-grpc-0.3.0.jar:0.3.0]
	at org.apache.servicecomb.saga.omega.connector.grpc.saga.GrpcCompensateStreamObserver.onNext(GrpcCompensateStreamObserver.java:31) ~[omega-connector-grpc-0.3.0.jar:0.3.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:407) [grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519) [grpc-core-1.14.0.jar:1.14.0]
	... 5 common frames omitted

2018-11-05 15:56:53.541  INFO 51280 --- [pool-1-thread-1] .a.s.s.o.c.g.c.PushBackReconnectRunnable : Retry connecting to alpha at 139.159.148.80:8088
2018-11-05 15:56:53.558 ERROR 51280 --- [pool-1-thread-1] .a.s.s.o.c.g.c.PushBackReconnectRunnable : Failed to reconnect to alpha at 139.159.148.80:8088

io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[grpc-stub-1.14.0.jar:1.14.0]
	at org.apache.servicecomb.saga.pack.contract.grpc.TxEventServiceGrpc$TxEventServiceBlockingStub.onDisconnected(TxEventServiceGrpc.java:280) ~[pack-contract-grpc-0.3.0.jar:0.3.0]
	at org.apache.servicecomb.saga.omega.connector.grpc.saga.GrpcSagaClientMessageSender.onDisconnected(GrpcSagaClientMessageSender.java:75) ~[omega-connector-grpc-0.3.0.jar:0.3.0]
	at org.apache.servicecomb.saga.omega.connector.grpc.core.PushBackReconnectRunnable.run(PushBackReconnectRunnable.java:52) ~[omega-connector-grpc-0.3.0.jar:0.3.0]
	at org.apache.servicecomb.saga.omega.connector.grpc.core.PendingTaskRunner$1.run(PendingTaskRunner.java:44) [omega-connector-grpc-0.3.0.jar:0.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**and the transaction came as follow:**

![image](https://user-images.githubusercontent.com/18557622/47987308-27ec5880-e11a-11e8-9ebc-e4067d6c00fe.png)

****no SagaEndedEvent was found**

**the network is normal, can anyone hep me with this issue?**

**Comment by bigzengdotcom** [comment]
> From the stack trace , it looks like alpha have some trouble to invoke the omega service.
> 
> > Caused by: java.lang.IllegalArgumentException: argument type mismatch
> 
> Can you check if the Compensable method has the same parameters as the Compensable annotated method?

absolutely. if the Compensable method does not have  the same parameters as the Compensable annotated method , it will not run normally. so , i have written the same parameters as the Compensable annotated method . but it still go wrong

**Comment by zhfeng** [comment]
is it possible to share your test project ?

**Comment by Gannalyo** [comment]
Did you set the 'Compensable Method' parameter for the annotation @Compensable ?

**Comment by jimforcode** [comment]
i've  meet the same problem,
my code is:

`  @Compensable(compensationMethod = "cancel")
    public Integer  get(T1 t1){
        int res= t1Dao.insert(t1.getId(),t1.getName(),t1.getAge());
         return res;
    }
    public Integer cancel(T1 t1){
        System.out.println("--- 事务补偿机制开启 ---");
        System.out.println(t1);
        System.out.println("开始删除数据: "+t1Dao.delete(t1.getId()));
        System.out.println("---事务补偿机制结束---");
        return 1;
    }`

` @Transactional
    @SagaStart
    @Compensable(compensationMethod = "cancel")
    public Object get(T2 t2){
        int res=   t2Dao.insert(t2.getId(),t2.getName(),t2.getAge());
        Map<String, Object> uriVariables=new HashMap<>();
        uriVariables.put("id",t2.getId());
        uriVariables.put("name",t2.getName());
        uriVariables.put("age",t2.getAge());
        ResponseEntity<String> resStr=null;
        ResponseEntity<String> resStr2=null;
        resStr=  template.getForEntity(String.format("http://localhost:12000/t1?id=%s&name=%s&age=%d",t2.getId(),t2.getName(),t2.getAge()),String.class);
        System.out.println("server001:"+resStr.getBody());

        resStr2=  template.getForEntity(String.format("http://localhost:12002/t3?id=%s&name=%s&age=%d",t2.getId(),t2.getName(),t2.getAge()),String.class);

        System.out.println("server003:"+resStr2.getBody());

        return String.format("server001:%s ,server002:%s ,server003:%s",resStr.getBody(),res+"",resStr2.getBody());
    }

    public Object cancel(T2 t2){
        System.out.println("开始事务补偿机制 start  。。。。");
        System.out.println("开始事务补偿机制 end 。。。。");
         return "起点重合";
    }`

error msg :

![image](https://user-images.githubusercontent.com/13187186/50965225-5ae10d00-150c-11e9-92d8-7d86d34d7285.png)

![image](https://user-images.githubusercontent.com/13187186/50965252-6f250a00-150c-11e9-906d-fe06a37b2bf2.png)

![image](https://user-images.githubusercontent.com/13187186/50965366-ba3f1d00-150c-11e9-87b6-bc438462ce29.png)

**Comment by jimforcode** [comment]
i‘ve soved this problem,   othes lib cause this problem ,   auto compile plugs  dev-tools cause this problem.

**Comment by WillemJiang** [comment]
I just added [a FAQ document](https://github.com/apache/servicecomb-pack/blob/master/docs/faq/en/omega-cannot-run-command-from-alpha.md) if you want to check out more information about it.
