### ISSUE TITLE
pack tcc 调用第2个服务时报错

### ISSUE THREAD

**Issue by jinbinguo** [apache/servicecomb-pack#459]
使用java-chassis的consumer 和 provider， TCC事务的参与方抛出如下异常。
```
2019-05-08 09:17:21.324  INFO 676 --- [nio-9101-exec-9] o.a.s.qps.QpsControllerManager           : Create qpsController, configKey = [pkms-test]
2019-05-08 09:17:21.324  INFO 676 --- [nio-9101-exec-9] o.a.s.qps.QpsControllerManager           : Create qpsController, configKey = [pkms-test.pkms-test1-pack]
2019-05-08 09:17:21.324  INFO 676 --- [nio-9101-exec-9] o.a.s.qps.QpsControllerManager           : Create qpsController, configKey = [pkms-test.pkms-test1-pack.testAuditBillEntry]
2019-05-08 09:17:21.692 ERROR 676 --- [pool-2-thread-1] o.a.s.p.o.c.g.c.LoadBalanceSenderAdapter : Retry sending event ParticipationStartedEvent{globalTxId='null', localTxId='8944bbe9-a4bd-40ec-aff7-685fc9e51151', parentTxId='null', confirmMethod='public void com.peaksport.pkms.leanrtest1.service.Test1PackService.auditBill1_confirm(java.lang.String)', cancelMethod='public void com.peaksport.pkms.leanrtest1.service.Test1PackService.auditBill1_cancel(java.lang.String)'} due to failure

java.lang.NullPointerException: null
	at org.apache.servicecomb.pack.contract.grpc.GrpcParticipationStartedEvent$Builder.setGlobalTxId(GrpcParticipationStartedEvent.java:845) ~[pack-contract-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.connector.grpc.tcc.GrpcTccClientMessageSender.convertTo(GrpcTccClientMessageSender.java:146) ~[omega-connector-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.connector.grpc.tcc.GrpcTccClientMessageSender.participationStart(GrpcTccClientMessageSender.java:74) ~[omega-connector-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.connector.grpc.tcc.TccLoadBalanceSender$1.apply(TccLoadBalanceSender.java:49) ~[omega-connector-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.connector.grpc.tcc.TccLoadBalanceSender$1.apply(TccLoadBalanceSender.java:46) ~[omega-connector-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.connector.grpc.core.LoadBalanceSenderAdapter.doGrpcSend(LoadBalanceSenderAdapter.java:54) ~[omega-connector-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.connector.grpc.tcc.TccLoadBalanceSender.participationStart(TccLoadBalanceSender.java:46) [omega-connector-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.transaction.tcc.TccParticipatorAspect.advise(TccParticipatorAspect.java:62) [omega-transaction-0.4.0.jar:0.4.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174) [spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at com.peaksport.pkms.leanrtest1.service.Test1PackService$$EnhancerBySpringCGLIB$$56f66d0d.auditBill1(<generated>) ~[classes/:na]
	at com.peaksport.pkms.leanrtest1.controller.TestPack1Controller.testAuditBillEntry(TestPack1Controller.java:23) ~[classes/:na]
```

**Comment by liubao68** [comment]
This is because global transaction id is missed. Sometimes because handlers are forgotten if using servicecomb-java-chassiss

```
servicecomb:
    handler:  
          chain:  
            Provider:  
              default: qps-flowcontrol-provider,bizkeeper-provider,pack-provider  
            Consumer:  
              default: qps-flowcontrol-consumer,loadbalance,bizkeeper-consumer,pack-consumer  
```
see: https://github.com/huaweicse/cse-java-chassis-samples/blob/master/HouseAppWithSpringBoot2/common/src/main/resources/microservice.yaml for an example

**Comment by liubao68** [comment]
However, this should be an improvement for pack. NPE should be caught and give a verbose information on how to handle this.

**Comment by coolbeevip** [comment]
> However, this should be an improvement for pack. NPE should be caught and give a verbose information on how to handle this.

I will add the omega context verification.

**Comment by WillemJiang** [comment]
@jinbinguo  Can you try it from our snapshot repo?

**Comment by WillemJiang** [comment]
Close the issue as we already merge the patch into master branch.
