### ISSUE TITLE
java.sql.SQLSyntaxErrorException: Table 'saga.TL_TxTimeout' doesn't exist

### ISSUE THREAD

**Issue by wuyongCloud** [apache/servicecomb-pack#490]
branch:0.4.x

**Comment by coolbeevip** [comment]
> branch:0.4.x
Can you provide more information? 
1. Database vendor and version
2. The full stack trace in exception
3. Alpha launch parameters

**Comment by wuyongCloud** [comment]
@coolbeevip 

ver-0.4.0-exec.jar_default login successful 13:06:18.061 [main] INFO  org.apache.servicecomb.pack.alpha.server.AlphaConfig - Starting the EventScanner. 13:06:18.120 [main] INFO  org.apache.servicecomb.pack.alpha.server.GrpcStartable - Bind successful to inet socket address /0.0.0.0:8080 13:06:18.273 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources. 13:06:18.273 [main] INFO  com.netflix.config.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath. 13:06:18.403 [pool-2-thread-1] WARN  org.eclipse.persistence.session./file:/maven/saga/alpha-server-0.4.0-exec.jar_default -  org.eclipse.persistence.exceptions.DatabaseException:  Internal Exception: java.sql.SQLSyntaxErrorException: Table 'saga.TL_TxTimeout' doesn't exist Error Code: 1146 Call: INSERT INTO TL_TxTimeout (SURROGATEID, STATUS, VERSION) SELECT t0.SURROGATEID, ?, (t0.VERSION + ?) FROM TxTimeout t0 WHERE ((t0.STATUS <> ?) AND EXISTS (SELECT ? FROM TxEvent t1 WHERE (((t1.GLOBALTXID = t0.GLOBALTXID) AND (t1.LOCALTXID = t0.LOCALTXID)) AND (t1.TYPE <> t0.TYPE))) ) 	bind => [4 parameters bound] Query: UpdateAllQuery(referenceClass=TxTimeout sql="CREATE TEMPORARY TABLE IF NOT EXISTS TL_TxTimeout (SURROGATEID BIGINT NOT NULL, EVENTID BIGINT, EXPIRYTIME DATETIME, GLOBALTXID VARCHAR(255), INSTANCEID VARCHAR(255), LOCALTXID VARCHAR(255), PARENTTXID VARCHAR(255), SERVICENAME VARCHAR(255), STATUS VARCHAR(255), TYPE VARCHAR(255), VERSION BIGINT, PRIMARY KEY (SURROGATEID))") 	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:331) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:905) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect
--
  | (DatabaseAccessor.java:967) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:637) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:564) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2093) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:309) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:270) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.updateAllUsingTempTables(DatasourceCallQueryMechanism.java:899) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.updateAll(DatasourceCallQueryMechanism.java:861) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.queries.UpdateAllQuery.executeDatabaseQuery(UpdateAllQuery.java:154) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:810) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.queries.ModifyAllQuery.executeInUnitOfWork(ModifyAllQuery.java:148) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2979) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1892) ~[org.eclipse.persistence.core-2.7.1
  | .jar!/:?] 	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1874) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	at org.eclipse.persistence.internal.jpa.QueryImpl.executeUpdate(QueryImpl.java:300) ~[org.eclipse.persistence.jpa-2.7.1.jar!/:?] 	at org.springframework.data.jpa.repository.query.JpaQueryExecution$ModifyingExecution.doExecute(JpaQueryExecution.java:256) ~[spring-data-jpa-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:91) ~[spring-data-jpa-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:136) ~[spring-data-jpa-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:125) ~[spring-data-jpa-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605) ~[spring-data-commons-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.1.3.RELEASE.jar
  | !/:2.1.3.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135) ~[spring-data-jpa-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.3.RELEASE.jar!/:2.1.3.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java
  | :186) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.apache.servicecomb.pack.alpha.server.$Proxy138.updateStatusOfFinishedTx(Unknown Source) ~[?:0.4.0] 	at org.apache.servicecomb.pack.alpha.server.SpringTxTimeoutRepository.markTimeoutAsDone(SpringTxTimeoutRepository.java:59) ~[classes!/:0.4.0] 	at org.apache.servicecomb.pack.alpha.server.SpringTxTimeoutRepository$$FastClassBySpringCGLIB$$dda60806.invoke(<generated>) ~[classes!/:0.4.0] 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE] 	at org.apache.servicecomb.pack.alpha.server.SpringTxTimeoutRepository$$EnhancerBySpringCGLIB$$4cfe8ab5.markTimeoutAsDone(<generated>) ~[classes!/:0.4.0] 	at org.apache.servicecomb.pack.alpha.core.EventScanner.updateTimeoutStatus(EventScanner.java:115) ~[alpha-core-0.4.0.jar!/:0.4.0] 	at org.apache.servicecomb.pack.alpha.core.EventScanner.lambda$pollEvents$0(EventScanner.java:90) ~[alpha-core-0.4.0.jar!/:0.4.0] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_212] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_212] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_212] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] Caused by: java.sql.SQLSyntaxErrorException: Table 'saga.TL_TxTi
  | meout' doesn't exist 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.13.jar!/:8.0.13] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.13.jar!/:8.0.13] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.13.jar!/:8.0.13] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974) ~[mysql-connector-java-8.0.13.jar!/:8.0.13] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1113) ~[mysql-connector-java-8.0.13.jar!/:8.0.13] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-java-8.0.13.jar!/:8.0.13] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1381) ~[mysql-connector-java-8.0.13.jar!/:8.0.13] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1046) ~[mysql-connector-java-8.0.13.jar!/:8.0.13] 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.2.0.jar!/:?] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.2.0.jar!/:?] 	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:895) ~[org.eclipse.persistence.core-2.7.1.jar!/:?] 	... 54 more

**Comment by wuyongCloud** [comment]
mysql 5.7
use mysql profile

**Comment by coolbeevip** [comment]
> mysql 5.7
> use mysql profile

How did you run Alpha? Please show me your run command. 
e.g
```java
java -jar xxxxx
```

**Comment by wuyongCloud** [comment]
mvn clean install -DskipTests -Pdocker,spring-boot-2,mysql
[alpha-server.zip](https://github.com/apache/servicecomb-pack/files/3367330/alpha-server.zip)
@coolbeevip

**Comment by coolbeevip** [comment]
> mvn clean install -DskipTests -Pdocker,spring-boot-2,mysql
> [alpha-server.zip](https://github.com/apache/servicecomb-pack/files/3367330/alpha-server.zip)
> @coolbeevip

Are you using a mysql cluster?

**Comment by wuyongCloud** [comment]
@coolbeevip 就一个mysql,这个TL_TxTimeout 和TxTimeout有什么区别吗

**Comment by coolbeevip** [comment]
> @coolbeevip 就一个mysql,这个TL_TxTimeout 和TxTimeout有什么区别吗

我看微信群中有人提到 TL_开头的表是JPA要创建的临时表，你可以检查以下你的mysql是否有临时表权限

**Comment by WillemJiang** [comment]
对了，你的数据表是怎么创建的， Alpha是会自动帮助建表的。使用创建SQL是不会创建临时表的。

**Comment by wuyongCloud** [comment]
@WillemJiang sql脚本手动创建的

**Comment by wuyongCloud** [comment]
把saga下table都删除后，再次启动alpha,还会报这个错误

**Comment by lostpillow** [comment]
TxTimeoutEntityRepository这个类里有个注解：
@Query("UPDATE TxTimeout t "
      + "SET t.status = 'DONE' "
      + "WHERE t.status != 'DONE' AND EXISTS ("
      + "  SELECT t1.globalTxId FROM TxEvent t1 "
      + "  WHERE t1.globalTxId = t.globalTxId "
      + "    AND t1.localTxId = t.localTxId "
      + "    AND t1.type != t.type"
      + ")")
这个sql语句，eclipse.persistence.jpa在执行的时候，会把它解析成多个语句执行，先将符合条件的数据插入临时表，再进行后续动作。create 临时表的动作，对mysql来说，是gtid不安全的，所以需要在mysql的配置中将enforce_gtid_consistency设置成关闭，才可以运行。但是阿里云的mysql5.6以上的此开关不允许关闭，所以。。。。
