### ISSUE TITLE
配置两个saga微服务，第二个服务启动就会报错

### ISSUE THREAD

**Issue by 1260643258** [apache/servicecomb-pack#504]
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[grpc-stub-1.14.0.jar:1.14.0]
	at org.apache.servicecomb.pack.contract.grpc.TxEventServiceGrpc$TxEventServiceBlockingStub.onDisconnected(TxEventServiceGrpc.java:280) ~[pack-contract-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.connector.grpc.saga.GrpcSagaClientMessageSender.onDisconnected(GrpcSagaClientMessageSender.java:75) ~[omega-connector-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.connector.grpc.core.LoadBalanceSenderAdapter.onDisconnected(LoadBalanceSenderAdapter.java:80) ~[omega-connector-grpc-0.4.0.jar:0.4.0]
	at org.apache.servicecomb.pack.omega.spring.OmegaSpringConfig$1.run(OmegaSpringConfig.java:145) [omega-spring-starter-0.4.0.jar:0.4.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by WillemJiang** [comment]
From the stack trace, it looks like the Alpha just close the connection.  I need to know more information about your issue.

**Comment by zhfeng** [comment]
can you provide the configuration files of these two services ?

**Comment by 1260643258** [comment]
> 你能提供这两项服务的配置文件吗？

![image](https://user-images.githubusercontent.com/51845491/61344996-e5247800-a885-11e9-8f72-c205c891f8c8.png)

**Comment by coolbeevip** [comment]
https://servicecomb.apache.org/cn/docs/servicecomb-pack-eureka/

**Comment by WillemJiang** [comment]
@1260643258 有什么进展吗？

**Comment by Fxdemon** [comment]
你应该没有设置主从模式没有开启

**Comment by Fxdemon** [comment]
alpha.cluster.master.enabled=true
