### ISSUE TITLE
Cannot find the service with the instanceId XXXX, call the other instance. 

### ISSUE THREAD

**Issue by aresa7796** [apache/servicecomb-pack#549]
版本0.5.0，在k8s上，日志报错如下：

> 06:27:28.135 [pool-3-thread-1] INFO  org.apache.servicecomb.pack.alpha.core.CompositeOmegaCallback - Cannot find the service with the instanceId shop-svc-10.10.1.62, call the other instance.
06:27:28.135 [pool-3-thread-1] ERROR org.apache.servicecomb.pack.alpha.core.PushBackOmegaCallback - Failed to compensate service [shop-svc] instance [shop-svc-10.10.1.62] with method [shop-svc/src/service/product.CompstBatchProdtStock], global tx id [3e7941cc-ff10-4449-9331-2a9ff189153b] and local tx id [71eb95ed-7d74-4d05-8697-1b6b954e5eb3]
org.apache.servicecomb.pack.alpha.core.AlphaException: No such omega callback found for service shop-svc
	at org.apache.servicecomb.pack.alpha.core.CompositeOmegaCallback.compensate(CompositeOmegaCallback.java:53) ~[alpha-core-0.5.0-SNAPSHOT.jar!/:0.5.0-SNAPSHOT]
	at org.apache.servicecomb.pack.alpha.core.PushBackOmegaCallback.compensate(PushBackOmegaCallback.java:46) ~[alpha-core-0.5.0-SNAPSHOT.jar!/:0.5.0-SNAPSHOT]
	at org.apache.servicecomb.pack.alpha.core.PushBackOmegaCallback.lambda$compensate$0(PushBackOmegaCallback.java:49) ~[alpha-core-0.5.0-SNAPSHOT.jar!/:0.5.0-SNAPSHOT]
	at org.apache.servicecomb.pack.alpha.core.PendingTaskRunner.lambda$run$0(PendingTaskRunner.java:39) ~[alpha-core-0.5.0-SNAPSHOT.jar!/:0.5.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by WillemJiang** [comment]
可否确认shop-svc-10.10.1.62 实例还在运行？
Pack并没有绑定特定的运行平台。

**Comment by coolbeevip** [comment]
如果你有alpha的完整日志，里面应该能找到你这个服务连接或者断开的日志信息

**Comment by tomatodady** [comment]
@WillemJiang 实例还在运行，日志中能看到alpha在反复调用实例的补偿函数，但就像日志里显示的，始终找不到；因为之前中断了服务进行升级，不知道是不是alpha不认启动后的实例（就算服务名和ip都没变）？

**Comment by WillemJiang** [comment]
@aresa7796 请问问题解决了吗？ 如果没有，看能不能提供更详细的信息。
