### ISSUE TITLE
akka.actor.ActorNotFound: Actor not found for

### ISSUE THREAD

**Issue by Fxdemon** [apache/servicecomb-pack#550]
Caused by: akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://alpha-akka/), Path(/user/9cb2c448-09e7-4896-9a72-629a6a91539c)]
	at akka.actor.ActorSelection.$anonfun$resolveOne$1(ActorSelection.scala:70)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:60)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:77)
	at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:120)
	at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:114)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:76)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:312)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:303)
	at akka.actor.ActorSelection.resolveOne(ActorSelection.scala:68)
	at org.apache.servicecomb.pack.alpha.fsm.sink.SagaActorEventSender.send(SagaActorEventSender.java:70)
	... 2 more
2019-09-02 15:30:44.505 ERROR Fxdemon --- [torEventChannel] o.a.s.p.a.f.c.MemoryActorEventChannel    : akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://alpha-akka/), Path(/user/9cb2c448-09e7-4896-9a72-629a6a91539c)]
java.lang.RuntimeException: akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://alpha-akka/), Path(/user/9cb2c448-09e7-4896-9a72-629a6a91539c)]
	at org.apache.servicecomb.pack.alpha.fsm.sink.SagaActorEventSender.send(SagaActorEventSender.java:79)
	at org.apache.servicecomb.pack.alpha.fsm.channel.MemoryActorEventChannel$EventConsumer.run(MemoryActorEventChannel.java:60)
	at java.lang.Thread.run(Thread.java:748)
Caused by: akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://alpha-akka/), Path(/user/9cb2c448-09e7-4896-9a72-629a6a91539c)]
	at akka.actor.ActorSelection.$anonfun$resolveOne$1(ActorSelection.scala:70)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:60)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:77)
	at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:120)
	at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:114)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:76)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:312)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:303)
	at akka.actor.ActorSelection.resolveOne(ActorSelection.scala:68)
	at org.apache.servicecomb.pack.alpha.fsm.sink.SagaActorEventSender.send(SagaActorEventSender.java:70)
	... 2 more
2019-09-02 15:30:44.507 ERROR Fxdemon --- [torEventChannel] o.a.s.p.a.f.c.MemoryActorEventChannel

**Comment by Fxdemon** [comment]
saga状态机模式 这个异常是什么原因？

**Comment by liulzz** [comment]
> saga状态机模式 这个异常是什么原因？

0.5.0版本中actor获取是同步阻塞的模式，一旦超时，就会throw一个ActorNotFound的runtimexception，需要调整actor获取的超时时间或者等下一个版本采用异步的方式
```
  private static final Timeout lookupTimeout = new Timeout(Duration.create(1, TimeUnit.SECONDS));
```
