### ISSUE TITLE
org.springframework.kafka.KafkaException: Timed out waiting to get existing topics;

### ISSUE THREAD

**Issue by Fxdemon** [apache/servicecomb-pack#555]
2019-09-09 11:08:41.292  INFO Fxdemon --- [           main] o.a.k.c.u.AppInfoParser                  : Kafka commitId : fa14705e51bd2ce5
2019-09-09 11:09:11.308 ERROR Fxdemon --- [           main] o.s.k.c.KafkaAdmin                       : Could not configure topics
org.springframework.kafka.KafkaException: Timed out waiting to get existing topics; nested exception is java.util.concurrent.TimeoutException
	at org.springframework.kafka.core.KafkaAdmin.lambda$checkPartitions$2(KafkaAdmin.java:238)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.springframework.kafka.core.KafkaAdmin.checkPartitions(KafkaAdmin.java:213)
	at org.springframework.kafka.core.KafkaAdmin.addTopicsIfNeeded(KafkaAdmin.java:199)
	at org.springframework.kafka.core.KafkaAdmin.initialize(KafkaAdmin.java:169)
	at org.springframework.kafka.core.KafkaAdmin.afterSingletonsInstantiated(KafkaAdmin.java:139)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:862)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at org.apache.servicecomb.pack.alpha.server.AlphaApplication.main(AlphaApplication.java:29)
Caused by: java.util.concurrent.TimeoutException
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:274)
	at org.springframework.kafka.core.KafkaAdmin.lambda$checkPartitions$2(KafkaAdmin.java:216)
	... 15 more

**Comment by Fxdemon** [comment]
kafka_2.11-0.9.0.0.tgz 存在bug 升级版本0.10+

**Comment by Fxdemon** [comment]
kafka版本问题。

**Comment by sunshine69** [comment]
I hit the same issues, is there any more information about this issues and how to fix this? My kafka version is 2.3.1 if it is relevant. Thanks
