### ISSUE TITLE
Kyro Exception : Unable to find class.

### ISSUE THREAD

**Issue by twistycs** [apache/servicecomb-pack#653]
Service A call B, C, D by order.

D was error then call compensate method **C**.

WARN: [kryo] Unable to load class **C** with kryo's ClassLoader. Retrying with current..
2020-04-23 15:21:47.037 ERROR 22328 --- [ault-executor-1] o.a.s.p.o.c.g.c.ReconnectStreamObserver  : Failed to process grpc coordinate
command.

io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
        at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420) [grpc-stub-1.14.0.jar:1.14.0]
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:531) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.14.0.jar:1.14.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: org.apache.servicecomb.pack.omega.transaction.OmegaException: Unable to deserialize message
        at org.apache.servicecomb.pack.omega.format.KryoMessageFormat.deserialize(KryoMessageFormat.java:66) ~[omega-format-0.5.0.jar:0.5.0]
        at org.apache.servicecomb.pack.omega.connector.grpc.saga.GrpcCompensateStreamObserver.onNext(GrpcCompensateStreamObserver.java:57) ~[omega-connector-grpc-0.5.0.jar:0.5.0]
        at org.apache.servicecomb.pack.omega.connector.grpc.saga.GrpcCompensateStreamObserver.onNext(GrpcCompensateStreamObserver.java:31) ~[omega-connector-grpc-0.5.0.jar:0.5.0]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:407) [grpc-stub-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519) [grpc-core-1.14.0.jar:1.14.0]
        ... 5 common frames omitted
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: **C**
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:388) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:302) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:753) ~[kryo-4.0.1.jar:na]
        at org.apache.servicecomb.pack.omega.format.KryoMessageFormat.deserialize(KryoMessageFormat.java:61) ~[omega-format-0.5.0.jar:0.5.0]
        ... 11 common frames omitted

**Comment by WillemJiang** [comment]
It looks like a classload issue,  can you double check if the the class C is loadable for Service C.
If you are using some class enhance tech, it may cause some trouble when Kryo deserialize the compensation message.

**Comment by twistycs** [comment]
I'm not sure. Service A call B,C,D. and I stop service D for cancel at service C but error message show 
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: C
Then I will restart Service C and its work. i dont kwow why.

**Comment by WillemJiang** [comment]
How do you call the service C, Service D from Service A.  Are they in different processes?

**Comment by twistycs** [comment]
@SagaStart at service A and then call service C for insert customer and D for insert information car. Not complicated .

**Comment by coolbeevip** [comment]
> I'm not sure. Service A call B,C,D. and I stop service D for cancel at service C but error message show
> Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: C
> Then I will restart Service C and its work. i dont kwow why.

Does this problem happen every time?

**Comment by twistycs** [comment]
All the time. If I run service C before service D. Then I restart service C and do it again it can use normally. 


**Log in service D to cancel service C :**   
2020-04-28 15:31:17.516 ERROR 19916 --- [ault-executor-2] o.a.s.p.o.c.g.c.ReconnectStreamObserver  : Failed to process
grpc coordinate command.

io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
        at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420) [grpc-stub-1.14.0.jar:1.14.0]
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:531) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.14.0.jar:1.14.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: org.apache.servicecomb.pack.omega.transaction.OmegaException: Unable to deserialize message
        at org.apache.servicecomb.pack.omega.format.KryoMessageFormat.deserialize(KryoMessageFormat.java:66) ~[omega-format-0.5.0.jar:0.5.0]
        at org.apache.servicecomb.pack.omega.connector.grpc.saga.GrpcCompensateStreamObserver.onNext(GrpcCompensateStreamObserver.java:57) ~[omega-connector-grpc-0.5.0.jar:0.5.0]
        at org.apache.servicecomb.pack.omega.connector.grpc.saga.GrpcCompensateStreamObserver.onNext(GrpcCompensateStreamObserver.java:31) ~[omega-connector-grpc-0.5.0.jar:0.5.0]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:407) [grpc-stub-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) [grpc-core-1.14.0.jar:1.14.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519) [grpc-core-1.14.0.jar:1.14.0]
        ... 5 common frames omitted
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: **class C**
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:388) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:302) ~[kryo-4.0.1.jar:na]
        at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:753) ~[kryo-4.0.1.jar:na]
        at org.apache.servicecomb.pack.omega.format.KryoMessageFormat.deserialize(KryoMessageFormat.java:61) ~[omega-format-0.5.0.jar:0.5.0]
        ... 11 common frames omitted
Caused by: java.lang.ClassNotFoundException: **class C**
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_201]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_201]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_201]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_201]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_201]
        at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_201]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154) ~[kryo-4.0.1.jar:na]
        ... 17 common frames omitted

2020-04-28 15:31:17.519  INFO 19916 --- [pool-3-thread-1] .a.s.p.o.c.g.c.PushBackReconnectRunnable : Retry connecting to alpha at xx.xx.xx.xxx:xxxx
2020-04-28 15:31:17.531 ERROR 19916 --- [pool-3-thread-1] .a.s.p.o.c.g.c.PushBackReconnectRunnable : Failed to reconnect to alpha at xx.xx.xx.xxx:xxxx

io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222) ~[grpc-stub-1.14.0.jar:1.14.0]
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203) ~[grpc-stub-1.14.0.jar:1.14.0]
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[grpc-stub-1.14.0.jar:1.14.0]
        at org.apache.servicecomb.pack.contract.grpc.TxEventServiceGrpc$TxEventServiceBlockingStub.onDisconnected(TxEventServiceGrpc.java:280) ~[pack-contract-grpc-0.5.0.jar:0.5.0]
        at org.apache.servicecomb.pack.omega.connector.grpc.saga.GrpcSagaClientMessageSender.onDisconnected(GrpcSagaClientMessageSender.java:75) ~[omega-connector-grpc-0.5.0.jar:0.5.0]
        at org.apache.servicecomb.pack.omega.connector.grpc.core.PushBackReconnectRunnable.run(PushBackReconnectRunnable.java:52) ~[omega-connector-grpc-0.5.0.jar:0.5.0]
        at org.apache.servicecomb.pack.omega.connector.grpc.core.PendingTaskRunner$1.run(PendingTaskRunner.java:44) [omega-connector-grpc-0.5.0.jar:0.5.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]


===============================================
**Log in Saga Server :** 
2020-04-28 08:30:54.971 ERROR alpha-server --- [ult-executor-38] i.g.i.SerializingExecutor                : Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@2c781686
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:524)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:366)
        at org.apache.servicecomb.pack.alpha.server.fsm.GrpcOmegaCallback.disconnect(GrpcOmegaCallback.java:72)
        at org.apache.servicecomb.pack.alpha.server.fsm.GrpcSagaEventService.onDisconnected(GrpcSagaEventService.java:91)
        at org.apache.servicecomb.pack.contract.grpc.TxEventServiceGrpc$MethodHandlers.invoke(TxEventServiceGrpc.java:408)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:808)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
