### ISSUE TITLE
启动报错，服务端使用的是0.7.1

### ISSUE THREAD

**Issue by myVictor** [apache/servicecomb-pack#776]
10:08:35,023 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:08:35,023 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/E:/GitCode/common/common-attachment/common-attachment/target/classes/logback.xml]
10:08:35,105 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - Setting logger context name as [logs]
10:08:35,105 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:08:35,108 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:08:35,137 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:08:35,140 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
10:08:35,146 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2014838114 - No compression will be used
10:08:35,147 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2014838114 - Will use the pattern /opt/logs/attachment/output.%d{yyyy-MM-dd}.log for the active file
10:08:35,151 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/attachment/output.%d{yyyy-MM-dd}.log'.
10:08:35,151 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
10:08:35,153 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Jul 25 10:08:35 CST 2023
10:08:35,155 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /opt/logs/attachment/output.2023-07-25.log
10:08:35,155 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
10:08:35,156 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:08:35,156 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR_FILE]
10:08:35,156 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@202125197 - No compression will be used
10:08:35,156 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@202125197 - Will use the pattern /opt/logs/attachment/error.%d{yyyy-MM-dd}.log for the active file
10:08:35,157 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/attachment/error.%d{yyyy-MM-dd}.log'.
10:08:35,157 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
10:08:35,157 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Jul 25 10:08:35 CST 2023
10:08:35,159 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - Active log file name: /opt/logs/attachment/error.2023-07-25.log
10:08:35,159 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - File property is set to [null]
10:08:35,159 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:08:35,159 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SYNC_FILE]
10:08:35,159 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@330739404 - No compression will be used
10:08:35,160 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@330739404 - Will use the pattern /opt/logs/attachment/sync.%d{yyyy-MM-dd}.log for the active file
10:08:35,160 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/attachment/sync.%d{yyyy-MM-dd}.log'.
10:08:35,160 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
10:08:35,160 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Jul 25 10:08:35 CST 2023
10:08:35,161 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYNC_FILE] - Active log file name: /opt/logs/attachment/sync.2023-07-25.log
10:08:35,161 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYNC_FILE] - File property is set to [null]
10:08:35,161 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [log.sync] to DEBUG
10:08:35,161 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SYNC_FILE] to Logger[log.sync]
10:08:35,162 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.apache.ibatis] to TRACE
10:08:35,162 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Connection] to DEBUG
10:08:35,162 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Statement] to DEBUG
10:08:35,162 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.PreparedStatement] to DEBUG
10:08:35,162 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to ERROR
10:08:35,162 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:08:35,162 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR_FILE] to Logger[ROOT]
10:08:35,162 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:08:35,163 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@394df057 - Registering current configuration as safe fallback point
10:08:35,701 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - Setting logger context name as [logs]
10:08:35,701 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:08:35,701 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:08:35,701 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:08:35,701 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
10:08:35,702 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@15094126 - No compression will be used
10:08:35,702 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@15094126 - Will use the pattern /opt/logs/attachment/output.%d{yyyy-MM-dd}.log for the active file
10:08:35,702 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/attachment/output.%d{yyyy-MM-dd}.log'.
10:08:35,702 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
10:08:35,702 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Jul 25 10:08:35 CST 2023
10:08:35,703 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /opt/logs/attachment/output.2023-07-25.log
10:08:35,703 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
10:08:35,703 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:08:35,703 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR_FILE]
10:08:35,703 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1843743552 - No compression will be used
10:08:35,703 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1843743552 - Will use the pattern /opt/logs/attachment/error.%d{yyyy-MM-dd}.log for the active file
10:08:35,704 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/attachment/error.%d{yyyy-MM-dd}.log'.
10:08:35,704 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
10:08:35,704 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Jul 25 10:08:35 CST 2023
10:08:35,705 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - Active log file name: /opt/logs/attachment/error.2023-07-25.log
10:08:35,705 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - File property is set to [null]
10:08:35,705 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:08:35,705 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SYNC_FILE]
10:08:35,705 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1139609587 - No compression will be used
10:08:35,705 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1139609587 - Will use the pattern /opt/logs/attachment/sync.%d{yyyy-MM-dd}.log for the active file
10:08:35,706 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/logs/attachment/sync.%d{yyyy-MM-dd}.log'.
10:08:35,706 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
10:08:35,706 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Jul 25 10:08:35 CST 2023
10:08:35,706 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYNC_FILE] - Active log file name: /opt/logs/attachment/sync.2023-07-25.log
10:08:35,706 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYNC_FILE] - File property is set to [null]
10:08:35,706 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [log.sync] to DEBUG
10:08:35,706 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@388ffbc2 - Propagating DEBUG level on Logger[log.sync] onto the JUL framework
10:08:35,707 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SYNC_FILE] to Logger[log.sync]
10:08:35,707 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.apache.ibatis] to TRACE
10:08:35,707 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@388ffbc2 - Propagating TRACE level on Logger[com.apache.ibatis] onto the JUL framework
10:08:35,707 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Connection] to DEBUG
10:08:35,707 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@388ffbc2 - Propagating DEBUG level on Logger[java.sql.Connection] onto the JUL framework
10:08:35,707 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Statement] to DEBUG
10:08:35,707 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@388ffbc2 - Propagating DEBUG level on Logger[java.sql.Statement] onto the JUL framework
10:08:35,707 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.PreparedStatement] to DEBUG
10:08:35,707 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@388ffbc2 - Propagating DEBUG level on Logger[java.sql.PreparedStatement] onto the JUL framework
10:08:35,707 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@388ffbc2 - Propagating ERROR level on Logger[ROOT] onto the JUL framework
10:08:35,707 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to ERROR
10:08:35,707 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:08:35,707 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR_FILE] to Logger[ROOT]
10:08:35,707 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:08:35,707 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@11389053 - Registering current configuration as safe fallback point

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.7)

2023-07-25  10:08:42.949 [grpc-default-executor-2] ERROR org.apache.servicecomb.pack.omega.connector.grpc.core.ReconnectStreamObserver - Failed to process grpc coordinate command.
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2023-07-25  10:08:42.960 [pool-2-thread-1] ERROR org.apache.servicecomb.pack.omega.connector.grpc.core.PushBackReconnectRunnable - Failed to reconnect to alpha at weiservice.bolttruck.com:8182
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at org.apache.servicecomb.pack.contract.grpc.TxEventServiceGrpc$TxEventServiceBlockingStub.onDisconnected(TxEventServiceGrpc.java:323)
	at org.apache.servicecomb.pack.omega.connector.grpc.saga.GrpcSagaClientMessageSender.onDisconnected(GrpcSagaClientMessageSender.java:77)
	at org.apache.servicecomb.pack.omega.connector.grpc.core.PushBackReconnectRunnable.run(PushBackReconnectRunnable.java:52)
	at org.apache.servicecomb.pack.omega.connector.grpc.core.PendingTaskRunner$1.run(PendingTaskRunner.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2023-07-25  10:08:42.987 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping' defined in class path resource [org/springframework/web/servlet/config/annotation/DelegatingWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.IllegalStateException: No ServletContext set
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at com.cz073586.AttachmentApplication.main(AttachmentApplication.java:21)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.IllegalStateException: No ServletContext set
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 18 common frames omitted
Caused by: java.lang.IllegalStateException: No ServletContext set
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.resourceHandlerMapping(WebMvcConfigurationSupport.java:591)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 19 common frames omitted

**Comment by coolbeevip** [comment]
Please provide more specific information, like the startup command or parameter.
